### ISSUE TITLE
Try to duplicate less code 

### ISSUE THREAD

**Issue by hofnerb** [boost-R/gamboostLSS#24]
@ja-thomas, we should try to use better functional units to avoid duplication of code. Currently, we have a lot of spaghetti code instead of proper functional programming. 

Can we aim for that in the next release, i.e. after the initial release of the non-cyclic fitting?

**Comment by hofnerb** [comment]
Perhaps we can furthermore already use object orientation within the fitting algorithm

**Comment by ja-thomas** [comment]
Should be better now. The code could be made nicer in the future, but that would require major refactoring (maybe even some on mboost). I don't think I have the time for that currently, but we can keep the issue open if you want to.
