### ISSUE TITLE
Prepare new release version

### ISSUE THREAD

**Issue by hofnerb** [boost-R/gamboostLSS#34]
- [x] Merge devel to master
- [x] Check that all relvant issues are closed
- [x] Check that reference to novel gamboostLSS algorithm + stabsel paper is present in all relevant places
- [x] Check vignette against published paper. Results should be (more or less) identical.
- [x] Check that all citations are up to date
- [x] Make sure NEWS.Rd reflects all recent changes.

**Comment by hofnerb** [comment]
On the way to merge. PR seems possible now...

**Comment by hofnerb** [comment]
Is [#32](https://github.com/boost-R/gamboostLSS/issues/32) still present? It doesn't seem to be the case. However, we should check that the tutorial gives the same results as before. I've added a bullet point above.

**Comment by hofnerb** [comment]
Seems that everything is fine now. We only need to wait until mboost is on CRAN (as we now require mboost >= 2.8-0) in order to be able to set \code{mstop = 0}. Once this has happened, we can finally update the dates and follow the release SOPs to release the package.

**Comment by mayrandy** [comment]
Fantastic, thanks for all the hard work !

**Comment by hofnerb** [comment]
Start finalizing...
