### ISSUE TITLE
Delete stco_paper branch

### ISSUE THREAD

**Issue by ja-thomas** [boost-R/gamboostLSS#42]
The branch was actually in a wrong state... and still contained refactored stuff.

The correct branch is now stco_paper_outer_version (I can't force-push stco_paper since it's protected)

stco_paper branch should be deleted and stco_paper_outer_version protected

**Comment by hofnerb** [comment]
@ja-thomas: Can be deleted now. please rename the new branch `stco_paper_outer_version" to `stco_paper` afterwards.

**Comment by ja-thomas** [comment]
fixed `stco_paper` branch to the correct version and deleted `stco_paper_outer_version`

@hofnerb can you protect the `stco_paper` again? I don't have rights for that

**Comment by hofnerb** [comment]
Done.
