### ISSUE TITLE
cvrisk.nc_gamboostLSS exportation and default 

### ISSUE THREAD

**Issue by Almond-S** [boost-R/gamboostLSS#46]
cvrisk.nc_gamboostLSS is currently not exported, but obviously provides another default grid then the one for cvrisk.gamboostLSS. The second default is also reported in ?cvrisk.gamboostLSS/?cvrisk.nc_gamboostLSS.

I was a little confused with that and maybe it would already help to export cvrisk.nc_gamboostLSS to make differences more visible.

Best,
Almond

**Comment by hofnerb** [comment]
Absolutely, you are right. The current status is not optimal. I will export the object and add it to the manual.

**Comment by Almond-S** [comment]
Great, thank you!

Best,
Almond

Am 17.05.2017 4:30 nachm. schrieb "Benjamin Hofner" <
notifications@github.com>:
