### ISSUE TITLE
example code in families.Rd failes

### ISSUE THREAD

**Issue by sbrockhaus** [boost-R/gamboostLSS#53]
For me, `devtools::run_examples()` fails for ` families.Rd `, with 

```
## families object for new distribution
newStudentT <- Families(mu= newStudentTMu(mu=mu, df=df),
                        df=newStudentTDf(mu=mu, df=df))

#  Error in body(x@response) : 
#   trying to get slot "response" from an object of a basic class ("function") with no slots
```
To be honest, I am not into Families. So can someone else please check? 

PS: I run on: 
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
gamboostLSS_2.0-1

**Comment by mayrandy** [comment]
Thanks! I'll take a look into this...

**Comment by mayrandy** [comment]
I did have some problems replicating this - for me everything worked fine.   

However, then I loaded the 'gamlss' package 

```
The following object is masked from ‘package:mboost’:

    Family
```

which then leads to the error.  So this a problem that only occurs when tha 'gamlss' package is loaded after 'gamboostLSS' and therefore 'mboost' as ```Family()``` exists both in 'gamlss.dist' and 'mboost'.

**Comment by mayrandy** [comment]
I just fix that by using ```mboost::Family``` in the examples -> that is not a very elegant way but solves the problem...

**Comment by sbrockhaus** [comment]
thank you very much. yes, I had loaded the gamlss package as well. old mistake I should have started a completely empty R session and check again...
