### ISSUE TITLE
predint() not working when multiple variables are included within a single baselearner

### ISSUE THREAD

**Issue by leirnessjb** [boost-R/gamboostLSS#55]
```
library("gamboostLSS")
set.seed(7)
data <- data.frame(x1 = runif(400, -1, 1),
                   x2 = runif(400, -1, 1),
                   x3 = runif(400, -1, 1),
                   x4 = runif(400, -1, 1))
data$y <- rnorm(400, 4 * data$x1 + 2 * data$x3)

gb <- gamboostLSS(y ~ btree(x1, x2, x3, x4), data = data, method = "noncyclic")

## error:
predint(gb, which = "x1")
```

possible fix:
replace `pred_vars <- unique(unlist(pred_vars))` with `pred_vars <- unique(trimws(unlist(strsplit(unlist(pred_vars), ","))))` in the predint() function

**Comment by hofnerb** [comment]
@mayrandy can you check the fix and include it if all tests and checks pass? Thanks a lot

**Comment by mayrandy** [comment]
Thanks @leirnessjb for finding this! The potential fit leads to other problems - but we will surely find a solucion

**Comment by mayrandy** [comment]
My mistake, I was the one leading to other problems ;-) - the fix by @leirnessjb works fine, thanks!!
