### ISSUE TITLE
Package not available via CRAN

### ISSUE THREAD

**Issue by nbsmokee** [boost-R/gamboostLSS#59]
Currently it seems impossible to obtain the package via CRAN:

```
> install.packages("gamboostLSS")
Installing package into **********************
(as ‘lib’ is unspecified)
Warning message:
package ‘gamboostLSS’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```
and also [https://cran.r-project.org/package=gamboostLSS](https://cran.r-project.org/package=gamboostLSS) says the following:
![homee 2022-05-09 14:27:48](https://user-images.githubusercontent.com/64212715/167409916-f9e7794b-8e8c-4ec2-b1b0-37996d02f57a.png)

**Comment by hofnerb** [comment]
As noted the packae is currently archieved. We resubmitted a new version but are still waiting for the CRAN review and approval. In the meantime you can either install the archived version or the latest github version e.g. using devtools as indicated in the Readme:

```R
library("devtools")
install_github("boost-R/gamboostLSS")
library("gamboostLSS")
```
